create temp table tmp_001 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 16031111 group by 1 ;                                                        select * from tmp_001;  
create temp table tmp_002 as select count(*) From nation where n_nationkey <= 10 distributed randomly;                                                                       select * from tmp_002; 
create temp table tmp_003 as select * from orders where o_orderkey between  16261 and 16291 order by 1distributed randomly;                                                  select * from tmp_003; 
create temp table tmp_004 as select p_name,count(*) from part where p_partkey between 87644 and 87645 group by 1 order by 1distributed randomly;                             select * from tmp_004; 
create temp table tmp_005 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 1621 group by 1 distributed randomly;                                        select * from tmp_005; 
create temp table tmp_006 as select * from customer where c_custkey between 95287 and 95287 order by 1 distributed randomly;                                                 select * from tmp_006; 
create temp table tmp_007 as select * From nation where n_name = 'MOROCCO' distributed randomly;                                                                             select * from tmp_007; 
create temp table tmp_008 as select s_nationkey, count(*) from supplier where s_suppkey between 1111 and 1133 group by 1 order by 1distributed randomly;                     select * from tmp_008; 
create temp table tmp_009 as select s_name, count(*) from supplier where s_suppkey between 10910 and 10915 group by 1 order by 1distributed randomly;                        select * from tmp_009; 
create temp table tmp_010 as select  c_custkey, count(*) cnt  from  customer where  c_custkey in( 382828, 12822) group by 1 distributed randomly;                            select * from tmp_010; 
create temp table tmp_011 as select p_size, count(*)  from part where p_partkey between 585750 and 585752 group by 1 order by 1distributed randomly;                         select * from tmp_011; 
create temp table tmp_012 as select * from orders where o_orderkey between  1725 and 1765 order by 1distributed randomly;                                                    select * from tmp_012; 
create temp table tmp_013 as select s_address, count(*) from supplier where s_suppkey between 19111 and 19123 group by 1 order by 1distributed randomly;                     select * from tmp_013; 
create temp table tmp_014 as select c_address, count(*) from customer where c_custkey between 9587 and 9587 group by 1 order by 1 distributed randomly;                      select * from tmp_014; 
create temp table tmp_015 as select * from orders where o_orderkey between  1822 and 1880 order by 1distributed randomly;                                                    select * from tmp_015; 
create temp table tmp_016 as select  c_name, c_custkey  from  customer where  c_custkey in (95370, 105657, 95356) distributed randomly;                                      select * from tmp_016; 
create temp table tmp_017 as select c_phone, count(*) from customer where c_custkey between 987766 and 987768 group by 1  order by 1 distributed randomly;                   select * from tmp_017; 
create temp table tmp_018 as select o_custkey, count(*) from orders where o_custkey = 2155366 group by 1distributed randomly;                                                select * from tmp_018; 
create temp table tmp_019 as select * from    lineitem  where   l_orderkey = 1132333 distributed randomly;                                                                   select * from tmp_019; 
create temp table tmp_020 as select  c_name, c_custkey  from  customer where  c_custkey = 96786 distributed randomly;                                                        select * from tmp_020; 
create temp table tmp_021 as select o_custkey, count(*) from orders where o_custkey = 155377 group by 1distributed randomly;                                                 select * from tmp_021; 
create temp table tmp_022 as select * from orders where o_orderkey between  2928729 and 2929029 order by 1distributed randomly;                                              select * from tmp_022; 
create temp table tmp_023 as select c_comment, count(*) from customer where c_custkey between 58463 and 58465  group by 1 order by 1 distributed randomly;                   select * from tmp_023; 
create temp table tmp_024 as select c_name, count(*) from customer where c_custkey between 8744 and 8745 group by 1 order by 1 distributed randomly;                         select * from tmp_024; 
create temp table tmp_025 as select * from part where p_partkey = 1318  order by 1distributed randomly;                                                                      select * from tmp_025; 
create temp table tmp_026 as select * From nation where n_nationkey = 10 distributed randomly;                                                                               select * from tmp_026; 
create temp table tmp_027 as select o_custkey, count(*) from orders where o_custkey = 3353121 group by 1distributed randomly;                                                select * from tmp_027; 
create temp table tmp_028 as select * from orders where o_orderkey = 68227  order by 1distributed randomly;                                                                  select * from tmp_028; 
create temp table tmp_029 as select * From nation where n_name = 'EGYPT' distributed randomly;                                                                               select * from tmp_029; 
create temp table tmp_030 as select o_custkey, count(*) from orders where o_custkey = 172363 group by 1distributed randomly;                                                 select * from tmp_030; 
create temp table tmp_031 as select * from orders where o_orderkey = 1318  order by 1distributed randomly;                                                                   select * from tmp_031; 
create temp table tmp_032 as select o_custkey, count(*) from orders where o_custkey = 272633 group by 1distributed randomly;                                                 select * from tmp_032; 
create temp table tmp_033 as select p_name, count(*) from part where p_partkey between 191920 and 191922 group by 1 order by 1distributed randomly;                          select * from tmp_033; 
create temp table tmp_034 as select s_acctbal, count(*) from supplier where s_suppkey between 69696 and 69699 group by 1 order by 1distributed randomly;                     select * from tmp_034; 
create temp table tmp_035 as select c_nationkey, count(*) from customer where c_custkey between 11287 and 11287 group by 1 order by 1 distributed randomly;                  select * from tmp_035; 
create temp table tmp_036 as select p_type, count(*) from part where p_partkey between 49585 and 49585 group by 1 order by 1distributed randomly;                            select * from tmp_036; 
create temp table tmp_037 as select * from supplier where s_suppkey between 10782 and 10782 order by 1distributed randomly;                                                  select * from tmp_037; 
create temp table tmp_038 as select  c_name, c_custkey  from  customer where  c_custkey = 1818111 distributed randomly;                                                      select * from tmp_038; 
create temp table tmp_039 as select o_custkey, count(*) from orders where o_custkey = 2333    group by 1distributed randomly;                                                select * from tmp_039; 
create temp table tmp_040 as select * From nation where n_name = 'ETHIOPIA' distributed randomly;                                                                            select * from tmp_040; 
create temp table tmp_041 as select * from    lineitem  where   l_orderkey = 11601223 distributed randomly;                                                                  select * from tmp_041; 
create temp table tmp_042 as select * from orders where o_orderkey between  2727 and 2730 order by 1distributed randomly;                                                    select * from tmp_042; 
create temp table tmp_043 as select o_custkey, count(*) from orders where o_custkey = 3355967 group by 1distributed randomly;                                                select * from tmp_043; 
create temp table tmp_044 as select * From nation where n_name = 'VIETNAM' distributed randomly;                                                                             select * from tmp_044; 
create temp table tmp_045 as select p_partkey, count(*) from part where p_partkey between 10292 and 10291 group by 1 order by 1distributed randomly;                         select * from tmp_045; 
create temp table tmp_046 as select c_acctbal, count(*) from customer where c_custkey between 18273 and 18275 group by 1  order by 1 distributed randomly;                   select * from tmp_046; 
create temp table tmp_047 as select * From nation where n_nationkey = 1 distributed randomly;                                                                                select * from tmp_047; 
create temp table tmp_048 as select  c_name, count(*)  from  customer where  c_custkey = 104445  group by 1 order by 1distributed randomly;                                  select * from tmp_048; 
create temp table tmp_049 as select s_phone, count(*) from supplier where s_suppkey between 1234 and 1237 group by 1 order by 1distributed randomly;                         select * from tmp_049; 
create temp table tmp_050 as select  c_name, c_custkey  from  customer where  c_custkey = 17171 distributed randomly;                                                        select * from tmp_050; 
create temp table tmp_051 as select s_acctbal, count(*) from supplier where s_suppkey between 9876 and 9877 group by 1 order by 1distributed randomly;                       select * from tmp_051; 
create temp table tmp_052 as select * from orders where o_orderkey between  12625 and 12725 order by 1distributed randomly;                                                  select * from tmp_052; 
create temp table tmp_053 as select * from    lineitem  where   l_orderkey = 221 distributed randomly;                                                                       select * from tmp_053; 
create temp table tmp_054 as select * from    lineitem  where   l_orderkey = 12221 order by 1 distributed randomly;                                                          select * from tmp_054; 
create temp table tmp_055 as select  c_custkey, count(*) cnt   from  customer where  c_custkey = 19383 group by 1 order by 1distributed randomly;                            select * from tmp_055; 
create temp table tmp_056 as select * from orders where o_orderkey between  191919 and 191940 order by 1distributed randomly;                                                select * from tmp_056; 
create temp table tmp_057 as select count(*) from part where p_partkey between 3030 and 3031 order by 1distributed randomly;                                                 select * from tmp_057; 
create temp table tmp_058 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 1602111 group by 1 distributed randomly;                                     select * from tmp_058; 
create temp table tmp_059 as select count(*) From nation where n_nationkey <= 4 distributed randomly;                                                                        select * from tmp_059; 
create temp table tmp_060 as select * from orders where o_orderkey between  23261 and 23291 order by 1distributed randomly;                                                  select * from tmp_060; 
create temp table tmp_061 as select p_name, count(*) from part where p_partkey between 97644 and 97645 group by 1 order by 1distributed randomly;                            select * from tmp_061; 
create temp table tmp_062 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 15521 group by 1 distributed randomly;                                       select * from tmp_062; 
create temp table tmp_063 as select * from customer where c_custkey between 1295287 and 1295287 order by 1 distributed randomly;                                             select * from tmp_063; 
create temp table tmp_064 as select * From nation where n_name = 'MOROCCO' distributed randomly;                                                                             select * from tmp_064; 
create temp table tmp_065 as select s_nationkey, count(*) from supplier where s_suppkey between 2211 and 2233 group by 1 order by 1distributed randomly;                     select * from tmp_065; 
create temp table tmp_066 as select s_name, count(*) from supplier where s_suppkey between 30910 and 30915 group by 1 order by 1distributed randomly;                        select * from tmp_066; 
create temp table tmp_067 as select  c_custkey, count(*) cnt  from  customer where  c_custkey in( 3332828, 1212822) group by 1 distributed randomly;                         select * from tmp_067; 
create temp table tmp_068 as select p_size, count(*)  from part where p_partkey between 445750 and 445752 group by 1 order by 1distributed randomly;                         select * from tmp_068; 
create temp table tmp_069 as select * from orders where o_orderkey between  16725 and 16765 order by 1distributed randomly;                                                  select * from tmp_069; 
create temp table tmp_070 as select s_address, count(*) from supplier where s_suppkey between 40111 and 40123 group by 1 order by 1distributed randomly;                     select * from tmp_070; 
create temp table tmp_071 as select c_address, count(*) from customer where c_custkey between 19587 and 19587 group by 1 order by 1 distributed randomly;                    select * from tmp_071; 
create temp table tmp_072 as select * from orders where o_orderkey between  1322 and 1380 order by 1distributed randomly;                                                    select * from tmp_072; 
create temp table tmp_073 as select  c_name, c_custkey  from  customer where  c_custkey in (9370, 5657, 915356) distributed randomly;                                        select * from tmp_073; 
create temp table tmp_074 as select o_custkey, count(*) from orders where o_custkey = 16262633 group by 1distributed randomly;                                               select * from tmp_074; 
create temp table tmp_075 as select c_phone, count(*) from customer where c_custkey between 9837766 and 9837768 group by 1  order by 1 distributed randomly;                 select * from tmp_075; 
create temp table tmp_076 as select o_custkey, count(*) from orders where o_custkey = 885366 group by 1distributed randomly;                                                 select * from tmp_076; 
create temp table tmp_077 as select * from    lineitem  where   l_orderkey = 83734 distributed randomly;                                                                     select * from tmp_077; 
create temp table tmp_078 as select * From nation where n_name = 'MOROCCO' distributed randomly;                                                                             select * from tmp_078; 
create temp table tmp_079 as select s_nationkey, count(*) from supplier where s_suppkey between 2211 and 2233 group by 1 order by 1distributed randomly;                     select * from tmp_079; 
create temp table tmp_080 as select s_name, count(*) from supplier where s_suppkey between 66910 and 66915 group by 1 order by 1distributed randomly;                        select * from tmp_080; 
create temp table tmp_081 as select  c_custkey, count(*) cnt  from  customer where  c_custkey in( 352828, 10030,20202,33332, 12822) group by 1 distributed randomly;         select * from tmp_081; 
create temp table tmp_082 as select p_size, count(*)  from part where p_partkey between 985750 and 985752 group by 1 order by 1distributed randomly;                         select * from tmp_082; 
create temp table tmp_083 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 223133 group by 1 distributed randomly;                                      select * from tmp_083; 
create temp table tmp_084 as select count(*) From nation where n_nationkey between 10 and 30 distributed randomly;                                                           select * from tmp_084; 
create temp table tmp_085 as select * from orders where o_orderkey between  218393 and 218396 order by 1distributed randomly;                                                select * from tmp_085; 
create temp table tmp_086 as select p_name,count(*) from part where p_partkey between 83938 and 83940 group by 1 order by 1distributed randomly;                             select * from tmp_086; 
create temp table tmp_087 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 39373 group by 1 distributed randomly;                                       select * from tmp_087; 
create temp table tmp_088 as select * from customer where c_custkey between 484709 and 484711 order by 1 distributed randomly;                                               select * from tmp_088; 
create temp table tmp_089 as select * From nation where n_name = 'USA' distributed randomly;                                                                                 select * from tmp_089; 
create temp table tmp_090 as select s_nationkey, count(*) from supplier where s_suppkey between 8940 and 8944 group by 1 order by 1distributed randomly;                     select * from tmp_090; 
create temp table tmp_091 as select s_name, count(*) from supplier where s_suppkey between 18101 and 18111 group by 1 order by 1distributed randomly;                        select * from tmp_091; 
create temp table tmp_092 as select  c_custkey, count(*) cnt  from  customer where  c_custkey in( 908097, 9022) group by 1 distributed randomly;                             select * from tmp_092; 
create temp table tmp_093 as select p_size, count(*)  from part where p_partkey between 12212 and 12223 group by 1 order by 1distributed randomly;                           select * from tmp_093; 
create temp table tmp_094 as select * from orders where o_orderkey between  1121 and 1121 order by 1distributed randomly;                                                    select * from tmp_094; 
create temp table tmp_095 as select s_address, count(*) from supplier where s_suppkey between 34353 and 34355 group by 1 order by 1distributed randomly;                     select * from tmp_095; 
create temp table tmp_096 as select c_address, count(*) from customer where c_custkey between 9696 and 9699 group by 1 order by 1 distributed randomly;                      select * from tmp_096; 
create temp table tmp_097 as select * from orders where o_orderkey between  978978 and 978980 order by 1distributed randomly;                                                select * from tmp_097; 
create temp table tmp_098 as select  c_name, c_custkey  from  customer where  c_custkey in (970, 1057, 953536) distributed randomly;                                         select * from tmp_098; 
create temp table tmp_099 as select o_custkey, count(*) from orders where o_custkey = 252353 group by 1distributed randomly;                                                 select * from tmp_099; 
create temp table tmp_100 as select c_phone, count(*) from customer where c_custkey between 74754 and 74757 group by 1  order by 1 distributed randomly;                     select * from tmp_100; 
create temp table tmp_101 as select o_custkey, count(*) from orders where o_custkey = 3723724 group by 1distributed randomly;                                                select * from tmp_101; 
create temp table tmp_102 as select * from    lineitem  where   l_orderkey = 131531 distributed randomly;                                                                    select * from tmp_102; 
create temp table tmp_103 as select  c_name, c_custkey  from  customer where  c_custkey = 13121 distributed randomly;                                                        select * from tmp_103; 
create temp table tmp_104 as select o_custkey, count(*) from orders where o_custkey = 123132 group by 1distributed randomly;                                                 select * from tmp_104; 
create temp table tmp_105 as select * from orders where o_orderkey between  63768 and 63790 order by 1distributed randomly;                                                  select * from tmp_105; 
create temp table tmp_106 as select c_comment, count(*) from customer where c_custkey between 745754 and 745760  group by 1 order by 1 distributed randomly;                 select * from tmp_106; 
create temp table tmp_107 as select c_name, count(*) from customer where c_custkey between 754257 and 754260 group by 1 order by 1 distributed randomly;                     select * from tmp_107; 
create temp table tmp_108 as select * from part where p_partkey = 97696  order by 1distributed randomly;                                                                     select * from tmp_108; 
create temp table tmp_109 as select * From nation where n_nationkey = 45 distributed randomly;                                                                               select * from tmp_109; 
create temp table tmp_110 as select o_custkey, count(*) from orders where o_custkey = 745743 group by 1distributed randomly;                                                 select * from tmp_110; 
create temp table tmp_111 as select * from orders where o_orderkey = 846865  order by 1distributed randomly;                                                                 select * from tmp_111; 
create temp table tmp_112 as select * From nation where n_name = 'JAPAN' distributed randomly;                                                                               select * from tmp_112; 
create temp table tmp_113 as select o_custkey, count(*) from orders where o_custkey = 65896 group by 1distributed randomly;                                                  select * from tmp_113; 
create temp table tmp_114 as select * from orders where o_orderkey = 57673  order by 1distributed randomly;                                                                  select * from tmp_114; 
create temp table tmp_115 as select o_custkey, count(*) from orders where o_custkey = 79765 group by 1distributed randomly;                                                  select * from tmp_115; 
create temp table tmp_116 as select p_name, count(*) from part where p_partkey between 57845 and 57850 group by 1 order by 1distributed randomly;                            select * from tmp_116; 
create temp table tmp_117 as select s_acctbal, count(*) from supplier where s_suppkey between 747352 and 747356 group by 1 order by 1distributed randomly;                   select * from tmp_117; 
create temp table tmp_118 as select c_nationkey, count(*) from customer where c_custkey between 8368 and 8370 group by 1 order by 1 distributed randomly;                    select * from tmp_118; 
create temp table tmp_119 as select p_type, count(*) from part where p_partkey between 5733473 and 5733475 group by 1 order by 1distributed randomly;                        select * from tmp_119; 
create temp table tmp_120 as select * from supplier where s_suppkey between 57457 and 57470 order by 1distributed randomly;                                                  select * from tmp_120; 
create temp table tmp_121 as select  c_name, c_custkey  from  customer where  c_custkey = 35421 distributed randomly;                                                        select * from tmp_121; 
create temp table tmp_122 as select o_custkey, count(*) from orders where o_custkey = 243521    group by 1distributed randomly;                                              select * from tmp_122; 
create temp table tmp_123 as select * From nation where n_name = 'SWISS' distributed randomly;                                                                               select * from tmp_123; 
create temp table tmp_124 as select * from    lineitem  where   l_orderkey = 35131 distributed randomly;                                                                     select * from tmp_124; 
create temp table tmp_125 as select * from orders where o_orderkey between  4124 and 4126 order by 1distributed randomly;                                                    select * from tmp_125; 
create temp table tmp_126 as select o_custkey, count(*) from orders where o_custkey = 1435214 group by 1distributed randomly;                                                select * from tmp_126; 
create temp table tmp_127 as select * From nation where n_name = 'DENMARK' distributed randomly;                                                                             select * from tmp_127; 
create temp table tmp_128 as select p_partkey, count(*) from part where p_partkey between 75327 and 75330 group by 1 order by 1distributed randomly;                         select * from tmp_128; 
create temp table tmp_129 as select c_acctbal, count(*) from customer where c_custkey between 643634 and 643638 group by 1  order by 1 distributed randomly;                 select * from tmp_129; 
create temp table tmp_130 as select * From nation where n_nationkey = 8 distributed randomly;                                                                                select * from tmp_130; 
create temp table tmp_131 as select  c_name, count(*)  from  customer where  c_custkey = 97697  group by 1 order by 1distributed randomly;                                   select * from tmp_131; 
create temp table tmp_132 as select s_phone, count(*) from supplier where s_suppkey between 75472 and 75476 group by 1 order by 1distributed randomly;                       select * from tmp_132; 
create temp table tmp_133 as select  c_name, c_custkey  from  customer where  c_custkey = 125125 distributed randomly;                                                       select * from tmp_133; 
create temp table tmp_134 as select s_acctbal, count(*) from supplier where s_suppkey between 68348 and 68360 group by 1 order by 1distributed randomly;                     select * from tmp_134; 
create temp table tmp_135 as select * from orders where o_orderkey between  724572 and 724576 order by 1distributed randomly;                                                select * from tmp_135; 
create temp table tmp_136 as select * from    lineitem  where   l_orderkey = 2346 distributed randomly;                                                                      select * from tmp_136; 
create temp table tmp_137 as select * from    lineitem  where   l_orderkey = 121311 order by 1 distributed randomly;                                                         select * from tmp_137; 
create temp table tmp_138 as select  c_custkey, count(*) cnt   from  customer where  c_custkey = 47373 group by 1 order by 1distributed randomly;                            select * from tmp_138; 
create temp table tmp_139 as select * from orders where o_orderkey between  71373 and 71375 order by 1distributed randomly;                                                  select * from tmp_139; 
create temp table tmp_140 as select count(*) from part where p_partkey between 317331 and 317335 order by 1distributed randomly;                                             select * from tmp_140; 
create temp table tmp_141 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 237327 group by 1 distributed randomly;                                      select * from tmp_141; 
create temp table tmp_142 as select count(*) From nation where n_nationkey <= 8 distributed randomly;                                                                        select * from tmp_142; 
create temp table tmp_143 as select * from orders where o_orderkey between  73247 and 73250 order by 1distributed randomly;                                                  select * from tmp_143; 
create temp table tmp_144 as select p_name,count(*) from part where p_partkey between 834832 and 834832 group by 1 order by 1distributed randomly;                           select * from tmp_144; 
create temp table tmp_145 as select l_orderkey, count(*) from    lineitem  where   l_orderkey = 72754 group by 1 distributed randomly;                                       select * from tmp_145; 
create temp table tmp_146 as select * from customer where c_custkey between 84275 and 84280 order by 1 distributed randomly;                                                 select * from tmp_146; 
create temp table tmp_147 as select * From nation where n_name = 'MOROCCO' distributed randomly;                                                                             select * from tmp_147; 
create temp table tmp_148 as select s_nationkey, count(*) from supplier where s_suppkey between 75436 and 75440 group by 1 order by 1distributed randomly;                   select * from tmp_148; 
create temp table tmp_149 as select s_name, count(*) from supplier where s_suppkey between 732146 and 732146 group by 1 order by 1distributed randomly;                      select * from tmp_149; 
create temp table tmp_150 as select  c_custkey, count(*) cnt  from  customer where  c_custkey in( 642352, 642355) group by 1 distributed randomly;                           select * from tmp_150; 
create temp table tmp_151 as select p_size, count(*)  from part where p_partkey between 725346 and 725350 group by 1 order by 1distributed randomly;                         select * from tmp_151; 
create temp table tmp_152 as select * from orders where o_orderkey between  3253 and 3255 order by 1distributed randomly;                                                    select * from tmp_152; 
create temp table tmp_153 as select s_address, count(*) from supplier where s_suppkey between 643543 and 643545 group by 1 order by 1distributed randomly;                   select * from tmp_153; 
create temp table tmp_154 as select c_address, count(*) from customer where c_custkey between 265443 and 265446 group by 1 order by 1 distributed randomly;                  select * from tmp_154; 
create temp table tmp_155 as select * from orders where o_orderkey between  46353 and 46357 order by 1distributed randomly;                                                  select * from tmp_155; 
create temp table tmp_156 as select  c_name, c_custkey  from  customer where  c_custkey in (34543, 3333, 123421) distributed randomly;                                       select * from tmp_156; 
create temp table tmp_157 as select o_custkey, count(*) from orders where o_custkey = 13413 group by 1distributed randomly;                                                  select * from tmp_157; 
create temp table tmp_158 as select c_phone, count(*) from customer where c_custkey between 435243 and 435245 group by 1  order by 1 distributed randomly;                   select * from tmp_158; 
create temp table tmp_159 as select o_custkey, count(*) from orders where o_custkey = 456345 group by 1distributed randomly;                                                 select * from tmp_159; 
create temp table tmp_160 as select * from    lineitem  where   l_orderkey = 745764 distributed randomly;                                                                    select * from tmp_160; 
create temp table tmp_161 as select * From nation where n_name = 'CHINA' distributed randomly;                                                                               select * from tmp_161; 
create temp table tmp_162 as select s_nationkey, count(*) from supplier where s_suppkey between 8657 and 8660 group by 1 order by 1distributed randomly;                     select * from tmp_162; 
create temp table tmp_163 as select s_name, count(*) from supplier where s_suppkey between 86575 and 86580 group by 1 order by 1distributed randomly;                        select * from tmp_163; 
create temp table tmp_164 as select  c_custkey, count(*) cnt  from  customer where  c_custkey in( 56436, 45645,56456,456, 64654) group by 1 distributed randomly;            select * from tmp_164; 
create temp table tmp_165 as select p_size, count(*)  from part where p_partkey between 46546 and 46550 group by 1 order by 1distributed randomly;                           select * from tmp_165;  
